#!/usr/bin/env python3
"""Generate the firmware's 4-bit Source Han Sans UI character subset."""

import argparse
import hashlib
import re
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE_SUFFIXES = {".c", ".h", ".cpp", ".hpp"}
FALLBACK = "□"


def scan_characters() -> str:
    chars = set()
    quoted = re.compile(r'"(?:\\.|[^"\\])*"')
    for path in sorted((ROOT / "main").iterdir()):
        if path.suffix not in SOURCE_SUFFIXES or path.name.startswith("ui_font_source_han_"):
            continue
        text = path.read_text(encoding="utf-8")
        for literal in quoted.findall(text):
            for char in literal:
                codepoint = ord(char)
                # Keep every printable non-ASCII character used by a runtime
                # string.  Limiting this to CJK ideographs missed UI
                # punctuation such as U+00B7 MIDDLE DOT and U+FF0F FULLWIDTH
                # SOLIDUS, which then rendered as fallback boxes.
                if codepoint >= 0x80 and char.isprintable():
                    chars.add(char)
    # Formatted clock/countdown values can emit any digit even when the source
    # contains only a printf pattern, so these ten glyphs are genuinely part
    # of the runtime subset rather than optional Latin coverage.
    chars.update("0123456789:")
    # Keep the complete printable ASCII range. It is tiny compared with CJK,
    # covers every English UI label and punctuation mark, and prevents a new
    # English string from silently rendering spaces or punctuation as boxes.
    chars.update(chr(codepoint) for codepoint in range(0x20, 0x7f))
    chars.add(FALLBACK)
    return "".join(sorted(chars, key=ord))


def pack_4bpp(image: Image.Image) -> bytes:
    values = [min(15, (value + 8) // 17) for value in image.get_flattened_data()]
    packed = bytearray()
    for index in range(0, len(values), 2):
        high = values[index]
        low = values[index + 1] if index + 1 < len(values) else 0
        packed.append((high << 4) | low)
    return bytes(packed)


def format_bytes(data: bytes) -> str:
    rows = []
    for index in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in data[index:index + 16]) + ",")
    return "\n".join(rows)


def generate(font_path: Path, pixel_size: int, requested_characters: str | None = None) -> None:
    characters = ("".join(sorted(set(requested_characters + FALLBACK), key=ord))
                  if requested_characters else scan_characters())
    font = ImageFont.truetype(str(font_path), pixel_size)
    missing_mask = font.getmask("\U0010ffff")
    missing_signature = (missing_mask.size, bytes(missing_mask))
    missing = []
    for char in characters:
        mask = font.getmask(char)
        if (mask.size, bytes(mask)) == missing_signature:
            missing.append(char)
    if missing:
        raise SystemExit(f"font is missing required characters: {''.join(missing)}")

    ascent, descent = font.getmetrics()
    glyph_rows = []
    bitmap = bytearray()

    for char in characters:
        left, top, right, bottom = font.getbbox(char, anchor="ls")
        # One transparent pixel around FreeType's ink bounds prevents edge
        # clipping while preserving the real baseline and advance.
        width = max(1, right - left + 2)
        height = max(1, bottom - top + 2)
        image = Image.new("L", (width, height), 0)
        draw = ImageDraw.Draw(image)
        draw.text((1 - left, 1 - top), char, font=font, fill=255, anchor="ls")
        packed = pack_4bpp(image)
        glyph_rows.append((ord(char), len(bitmap), len(packed), width, height,
                           round(font.getlength(char)), left - 1, top - 1))
        bitmap.extend(packed)

    family = "Source Han Sans CN Medium"
    source_hash = hashlib.sha256(font_path.read_bytes()).hexdigest()
    header_path = ROOT / "main" / f"ui_font_source_han_{pixel_size}.h"
    source_path = ROOT / "main" / f"ui_font_source_han_{pixel_size}.c"
    charset_path = ROOT / "tools" / "ui_font_charset.txt"

    header_path.write_text(
        "#pragma once\n\n#include \"ui_font.h\"\n\n"
        f"extern const ui_font_t g_source_han_sans_cn_{pixel_size};\n",
        encoding="utf-8",
    )
    rows = "\n".join(
        f"    {{0x{cp:04x}, {offset}, {size}, {width}, {height}, {advance}, {xoff}, {yoff}}},"
        for cp, offset, size, width, height, advance, xoff, yoff in glyph_rows
    )
    source_path.write_text(
        "// Generated by tools/generate_ui_font.py; do not edit manually.\n"
        f"// Font: {family}, {pixel_size}px, source SHA-256 {source_hash}\n"
        f"// Subset: {len(characters)} glyphs, 4-bit grayscale, {len(bitmap)} bitmap bytes.\n"
        f"#include \"ui_font_source_han_{pixel_size}.h\"\n\n"
        "static const ui_glyph_t kGlyphs[] = {\n" + rows + "\n};\n\n"
        "static const uint8_t kBitmap[] = {\n" + format_bytes(bitmap) + "\n};\n\n"
        f"const ui_font_t g_source_han_sans_cn_{pixel_size} = {{\n"
        "    .glyphs = kGlyphs,\n"
        "    .bitmap = kBitmap,\n"
        f"    .glyph_count = {len(characters)},\n"
        f"    .bitmap_size = {len(bitmap)},\n"
        f"    .fallback_codepoint = 0x{ord(FALLBACK):04x},\n"
        f"    .pixel_size = {pixel_size},\n"
        f"    .ascent = {ascent},\n"
        f"    .descent = {descent},\n"
        f"    .line_height = {ascent + descent},\n"
        "    .letter_spacing = 1,\n"
        "};\n",
        encoding="utf-8",
    )
    if requested_characters is None:
        charset_path.write_text(characters + "\n", encoding="utf-8")
    print(f"{family} {pixel_size}px: {len(characters)} glyphs, {len(bitmap)} bytes, "
          f"ascent={ascent}, descent={descent}")
    print(f"characters: {characters}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True, type=Path)
    parser.add_argument("--size", type=int, default=24)
    parser.add_argument("--characters", help="explicit runtime subset, e.g. 0123456789:")
    args = parser.parse_args()
    generate(args.font.resolve(), args.size, args.characters)


if __name__ == "__main__":
    main()
